### ISSUE TITLE
Install instructions fail

### ISSUE THREAD

**Issue by ianhi** [JBGreisman/mdtools#1]
Installing mdtraj via pip fails:

Result from running `python setup.py install`
```bash
mdtraj/rmsd/src/center.c:22:13: error: ‘n_frames’ not specified in enclosing ‘parallel’
   22 |     #pragma omp parallel for default(none) shared(coords, traces) \
      |             ^~~
mdtraj/rmsd/src/center.c:22:13: error: enclosing ‘parallel’
mdtraj/rmsd/src/center.c:27:27: error: ‘n_atoms’ not specified in enclosing ‘parallel’
   27 |         confp = &coords[k * n_atoms * 3];
      |                         ~~^~~~~~~~~
mdtraj/rmsd/src/center.c:22:13: error: enclosing ‘parallel’
   22 |     #pragma omp parallel for default(none) shared(coords, traces) \
      |             ^~~
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

A fix is to instead install mdtraj with conda:
`conda install -c conda-forge mdtraj`

**Comment by JBGreisman** [comment]
I removed the requirement in `setup.py` and added `mdtraj` to the installation instructions in the README. This is a temporary fix, but should at least make things behave as expected.

**Comment by ianhi** [comment]
you're a superhero 🦸

**Comment by JBGreisman** [comment]
Note: it seems that the mdtraj installation issue has been fixed https://github.com/mdtraj/mdtraj/issues/1475, and will be included in the next release
